-- MySQL Script generated by MySQL Workbench
-- Tue 24 Jul 2018 08:57:30 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`boletos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`boletos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vuelo` VARCHAR(255) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`bitacora_precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`bitacora_precios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `boleto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bitacora_precios_boleto_idx` (`boleto_id` ASC),
  CONSTRAINT `fk_bitacora_precios_boletos`
    FOREIGN KEY (`boleto_id`)
    REFERENCES `tienda`.`boletos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
